name: Build Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Verify Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: List Build Directory
        run: dir build/windows/x64/runner/Release

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

  