name: Build Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Verify Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Verify Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Linux
        run: flutter build linux

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/linux/runner/Release/
